/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  const routesList = {
    '404': '404',
    chainManagementChainIdExplorerLedgerBlockDetailHash:
      'chain-management-chainId-explorer-ledger-blockDetail-hash',
    chainManagementChainIdExplorerLedger:
      'chain-management-chainId-explorer-ledger',
    chainManagementChainIdExplorer: 'chain-management-chainId-explorer',
    chainManagementChainId: 'chain-management-chainId',
    chainManagementId: 'chain-management-id',
    hiId: 'hi-id',
    index: 'index',
    restfulPageView: 'restful-page-view',
  }

  return {
    provide: {
      typedRouter: nuxtApp.$router,
      routesList,
    },
  }
})
